# Site settings
title: toolbox
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://containertoolbx.org" # the base hostname & protocol for your site
sourceurl: "https://github.com/containers/containertoolbx.org"
description: "Toolbox: Easy Container Environments"

permalink: /:title/

# Build settings
markdown: kramdown
